export function getCardTable () {
    return [{
      code: 'card001',
      name: '原保险保费收入',
      icon: '../../../static/icon/3.png'
    }, {
      code: 'card002',
      name: '总资产/净资产',
      icon: '../../../static/icon/1.png'
    }, {
      code: 'card003',
      name: '净利润',
      icon: '../../../static/icon/7.png'
    }, {
      code: 'card004',
      name: '归属于母公司净利润',
      icon: '../../../static/icon/2.png'
    }, {
      code: 'card005',
      name: '综合偿付能力充足率',
      icon: '../../../static/icon/5.png'
    }, {
      code: 'card006',
      name: '百元保费净现金流',
      icon: '../../../static/icon/2.png'
    }, {
      code: 'card007',
      name: '同业市场份额',
      icon: '../../../static/icon/8.png'
    }, {
      code: 'card008',
      name: '综合赔付率/费用率/成本率',
      icon: '../../../static/icon/6.png'
    }, {
      code: 'card009',
      name: '净利润/承保利润',
      icon: '../../../static/icon/4.png'
    }, {
      code: 'card010',
      name: '保费收入（收付费）',
      icon: '../../../static/icon/3.png'
    }, {
      code: 'card011',
      name: '新业务价值',
      icon: '../../../static/icon/8.png'
    }, {
      code: 'card012',
      name: '短期险综合成本率',
      icon: '../../../static/icon/6.png'
    }, {
      code: 'card013',
      name: '规模保费（按日）',
      icon: '../../../static/icon/3.png'
    }, {
      code: 'card014',
      name: '资产管理费收入',
      icon: '../../../static/icon/3.png'
    }, {
      code: 'card015',
      name: '受托资产规模合计',
      icon: '../../../static/icon/1.png'
    }, {
      code: 'card016',
      name: '人均期缴产能',
      icon: '../../../static/icon/6.png'
    }, {
      code: 'card017',
      name: '原保险保费收入（按日）-计划',
      icon: '../../../static/icon/3.png'
    }, {
      code: 'card0118',
      name: '业务口径标准保费（按日）',
      icon: '../../../static/icon/5.png'
    }, {
      code: 'card019',
      name: '规模人力（按日）',
      icon: '../../../static/icon/5.png'
    }]
  }